name: Publish Docker

on:
  push:
    branches: [master]

# решить проблему с npm install --force для nest-typegoose,
# чтобы работали github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/toxanski/nestjs-practice-project/nestjs-practice-project
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"